### ISSUE TITLE
Dates are in ticks

### ISSUE THREAD

**Issue by fboucher** [jrummell/GhostToGitHubPagesConverter#1]
The dates are in ticks (ex: 2018-06-07-zip-push-deployment.md) not sure if it's the Ghost version that does that or if it was just not managed by the converter.

I'm exporting from Ghost 0.7

I did a Pull request #2

**Comment by jrummell** [comment]
Thanks for the PR!. It looks like the Ghost date format changed at some point. In my export dates are strings.

```json
{
    "id": 1,
    "uuid": "de30ea27-7815-48d1-8c9e-a8f3f080be93",
    "title": "Welcome to Ghost",
    "slug": "welcome-to-ghost",
    "markdown": "...",
    "mobiledoc": null,
    "html": "...",
    "image": null,
    "featured": 0,
    "page": 0,
    "status": "draft",
    "language": "en_US",
    "visibility": "public",
    "meta_title": null,
    "meta_description": null,
    "author_id": 1,
    "created_at": "2017-04-25 20:54:20",
    "created_by": 1,
    "updated_at": "2017-04-25 21:07:28",
    "updated_by": 1,
    "published_at": "2017-04-25 20:54:20",
    "published_by": 1,
    "amp": null
}
```

If you could update your PR to do a try parse for a unix timestamp and fall back on the unparsed value (date string), I'll merge it in.

**Comment by fboucher** [comment]
Good point!
I added a validation. And I also changed the date inside the file. 
In PR #2 
Let me know .

**Comment by jrummell** [comment]
Awesome, thank you!
